version: "3.8"

services:
  database:
    container_name: todo-database
    image: postgres:12-alpine
    volumes:
      - data-db:/var/lib/postgresql/data
      - ./server/prisma/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5433:5432
    networks:
      - todo-network
    env_file:
      - ./server/postgres.env

  backend:
    container_name: todo-server
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - todo-network
    env_file:
      - ./server/.env
    depends_on:
      - database

  frontend:
    container_name: todo-client
    build:
      context: ./client
      args:
        - API_ENDPOINT=http://localhost/api
    ports:
      - 8080:80
    networks:
      - todo-network
    depends_on:
      - backend

  web-server:
    container_name: web-server
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - todo-network
    depends_on:
      - database
      - backend
      - frontend

networks:
  todo-network:
    name: todo-network

volumes:
  data-db:
